### ISSUE TITLE
Could you add YAML ?

### ISSUE THREAD

**Issue by nicop311** [alpertuna/vim-header#41]
Hi, I was wondering if you could add the YAML syntax ?
(YAML Ain't Markup Language, https://en.wikipedia.org/wiki/YAML)

Thanks a lot, nice plugin :-)

**Comment by alpertuna** [comment]
Yaml support has been added.

Thank you :blush:

**Comment by nicop311** [comment]
Wow thank you, that was quick ! I updated the plugin and it works.

Here is the result on a minimal yaml file:
```yaml
# File              : myFile.yml
# Author            : myName
# Date              : 02.03.2018
# Last Modified Date: 02.03.2018
# Last Modified By  : myName
- nice: work
  it: was what I
- was:
  looking: "for !"
```
